// Team assignments with bet amounts and owners
const teamAssignments = {
    "Tennessee Titans": { owner: "Kris", bet: 10 },
    "Philadelphia Eagles": { owner: "Ross", bet: 45 },
    "Chicago Bears": { owner: "Kris", bet: 25 },
    "Denver Broncos": { owner: "James", bet: 35 },
    "Houston Texans": { owner: "Ross", bet: 46 },
    "New England Patriots": { owner: "James", bet: 35 },
    "Cincinnati Bengals": { owner: "James", bet: 30 },
    "Cleveland Browns": { owner: "James", bet: 26 },
    "Buffalo Bills": { owner: "Anh", bet: 51 },
    "Kansas City Chiefs": { owner: "Anh", bet: 46 },
    "Baltimore Ravens": { owner: "Peter", bet: 55 },
    "Dallas Cowboys": { owner: "James", bet: 23 },
    "New York Jets": { owner: "Peter", bet: 28 },
    "Seattle Seahawks": { owner: "Peter", bet: 39 },
    "Detroit Lions": { owner: "Peter", bet: 55 },
    "Green Bay Packers": { owner: "Anh", bet: 55 },
    "Tampa Bay Buccaneers": { owner: "Anh", bet: 48 },
    "New Orleans Saints": { owner: "James", bet: 24 },
    "Carolina Panthers": { owner: "Jamie", bet: 24 },
    "Atlanta Falcons": { owner: "Kris", bet: 35 },
    "San Francisco 49ers": { owner: "Kris", bet: 48 },
    "Arizona Cardinals": { owner: "Ross", bet: 35 },
    "New York Giants": { owner: "Jamie", bet: 25 },
    "Los Angeles Chargers": { owner: "Jamie", bet: 36 },
    "Miami Dolphins": { owner: "Jamie", bet: 26 },
    "Pittsburgh Steelers": { owner: "Jamie", bet: 37 },
    "Washington Commanders": { owner: "Ross", bet: 42 },
    "Indianapolis Colts": { owner: "Kris", bet: 25 },
    "Jacksonville Jaguars": { owner: "Kris", bet: 28 },
    "Minnesota Vikings": { owner: "Jamie", bet: 29 },
    "Los Angeles Rams": { owner: "Ross", bet: 32 },
    "Las Vegas Raiders": { owner: "Kris", bet: 29 }
};

// NFL team abbreviations mapping for API calls
const teamAbbreviations = {
    "Tennessee Titans": "TEN",
    "Philadelphia Eagles": "PHI",
    "Chicago Bears": "CHI",
    "Denver Broncos": "DEN",
    "Houston Texans": "HOU",
    "New England Patriots": "NE",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Buffalo Bills": "BUF",
    "Kansas City Chiefs": "KC",
    "Baltimore Ravens": "BAL",
    "Dallas Cowboys": "DAL",
    "New York Jets": "NYJ",
    "Seattle Seahawks": "SEA",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GB",
    "Tampa Bay Buccaneers": "TB",
    "New Orleans Saints": "NO",
    "Carolina Panthers": "CAR",
    "Atlanta Falcons": "ATL",
    "San Francisco 49ers": "SF",
    "Arizona Cardinals": "ARI",
    "New York Giants": "NYG",
    "Los Angeles Chargers": "LAC",
    "Miami Dolphins": "MIA",
    "Pittsburgh Steelers": "PIT",
    "Washington Commanders": "WSH",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAX",
    "Minnesota Vikings": "MIN",
    "Los Angeles Rams": "LAR",
    "Las Vegas Raiders": "LV"
};

// Alternative team names that might be returned by API
const teamNameMappings = {
    "Titans": "Tennessee Titans",
    "Eagles": "Philadelphia Eagles",
    "Bears": "Chicago Bears",
    "Broncos": "Denver Broncos",
    "Texans": "Houston Texans",
    "Patriots": "New England Patriots",
    "Bengals": "Cincinnati Bengals",
    "Browns": "Cleveland Browns",
    "Bills": "Buffalo Bills",
    "Chiefs": "Kansas City Chiefs",
    "Ravens": "Baltimore Ravens",
    "Cowboys": "Dallas Cowboys",
    "Jets": "New York Jets",
    "Seahawks": "Seattle Seahawks",
    "Lions": "Detroit Lions",
    "Packers": "Green Bay Packers",
    "Buccaneers": "Tampa Bay Buccaneers",
    "Saints": "New Orleans Saints",
    "Panthers": "Carolina Panthers",
    "Falcons": "Atlanta Falcons",
    "49ers": "San Francisco 49ers",
    "Cardinals": "Arizona Cardinals",
    "Giants": "New York Giants",
    "Chargers": "Los Angeles Chargers",
    "Dolphins": "Miami Dolphins",
    "Steelers": "Pittsburgh Steelers",
    "Commanders": "Washington Commanders",
    "Colts": "Indianapolis Colts",
    "Jaguars": "Jacksonville Jaguars",
    "Vikings": "Minnesota Vikings",
    "Rams": "Los Angeles Rams",
    "Raiders": "Las Vegas Raiders"
};
